MASTER_USERNAME = 'Master'
MASTER_PASSWORD = 'Pass'
USER_DETAILS_PICKLE_FILE = 'user_details.pickle'
DONOR_DETAILS_PICKLE_FILE = 'donor_details.pickle'
USER_LOG_FILE = 'user_activity.log'
DONOR_LOG_FILE = 'donor.log'
