from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
import config

def create_pdf(filename,receipt_number,title,name,org,contact_person,credit_date,credit_time,amount,currency, payment_mode,credit_reference,payment_date,receipt_disp_mode):
    directory=config.RECEIPT_DIRECTORY
    file_path=directory+'/'+filename
    if len(title)!=0:
        full_name=title+' '+name
    else:
        full_name=name
    can = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4
    can.setFont('Helvetica', 10)
    headerfooter='This is an Electronically Generated Receipt created on {} at {} by {}'.format(credit_date,credit_time,contact_person)
    can.drawCentredString(width/2,820, headerfooter)
    can.setLineWidth(2)
    can.setStrokeColorRGB(255, 0, 0)
    can.setFont('Helvetica', 18)
    logo_filename = 'static/images/cmu logo.png'
    can.drawImage(logo_filename, 10, 720, 50, 50)
    can.drawCentredString(width/2,750, 'DONATION RECEIPT & TRANSACTION DETAILS')
    can.line(95, 745,500, 745)
    can.drawString(220, 715, 'SPHINXCAPT.ORG')
    can.line(220, 710, 382, 710)
    can.setLineWidth(1.5)
    can.setStrokeColorRGB(0, 0, 0)
    can.line(0, 700, width, 700)
    can.setFont('Helvetica', 12)
    can.drawString(40, 670, "Date:")
    can.drawString(90, 670, credit_date)
    can.drawString(40, 640, "Time:")
    can.drawString(90, 640,credit_time)
    can.drawString(250, 670, "Receipt Number:")
    can.drawString(350, 670, receipt_number)
    can.drawString(250, 640, "Generated By:")
    can.drawString(350, 640, contact_person)
    can.line(0, 620, width, 620)
    can.drawString(70, 600, "Donor Name:")
    can.drawString(150, 600, full_name)
    can.drawString(70, 570, "Company/Organisation:")
    can.drawString(200, 570, org)
    can.drawString(70, 540, "Date of Donation:")
    can.drawString(170, 540, str(payment_date))
    can.drawString(350, 540, "Mode of Donation:")
    can.drawString(450, 540, payment_mode)
    can.drawString(70, 510, "Donated Amount:")
    can.drawString(170, 510, str(amount)+' '+currency)
    can.drawString(350, 510, "Transaction Reference:")
    can.drawString(480, 510, credit_reference)
    thankstring="Received with thanks {} {} from {} via {} as donation ".format(amount,currency,full_name,payment_mode)
    can.drawString(50, 460, thankstring)
    can.drawString(50, 445, "towards fund raising for Project SphinxCapt(www.Sphinxcapt.org).")
    can.setFillColorRGB(255,0,255)
    can.drawString(50, 400, "On behalf of SphinxCapt we thank you for your support and commitment towards the project.")
    can.setFillColorRGB(0,0,0)
    can.drawString(50, 360, contact_person)
    can.setFont('Helvetica', 10)
    can.drawCentredString(width/2,20, headerfooter)
    can.save()
